version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.cron
    volumes:
      - ./output:/app/output
      - ./bocfx.config:/app/bocfx.config
    restart: unless-stopped
